/**
 * Exports Image Paths
 * @function Images
 */
export const Images = {
  logo: require('../assets/Images/logo.png'),
  oculo: require('../assets/Images/smallLogo.png'),
  faceid: require('../assets/Images/faceid.png'),
  avatar: require('../assets/Images/avatar.png'),
  demoSummary: require('../assets/Images/demoSummary.png'),
  graph1: require('../assets/Images/graph1.png'),
  emoji1: require('../assets/Images/emoji1.png'),
  down: require('../assets/Images/down.png'),
  emoji5: require('../assets/Images/emoji5.png'),
  graph: require('../assets/Images/graph.png'),
  callibrateImg: require('../assets/Images/calli.png'),
  eyeLine: require('../assets/Images/eyeline.png'),
  sliderimage: require('../assets/Images/sliderimage.png'),
  rememberword: require('../assets/Images/rememberword.png'),
  twofa: require('../assets/Images/2fa.png'),
  speech: require('../assets/Images/speech.png'),
  typetobox: require('../assets/Images/typetobox.png'),
  speechtotext: require('../assets/Images/speechtotext.png'),
  stopspeech: require('../assets/Images/stopspeech.png'),
  man: require('../assets/Images/man.png'),
  manbold: require('../assets/Images/manbold.png'),
  rememberno: require('../assets/Images/rememberno.png'),
  speechno: require('../assets/Images/speechno.png'),
  typeno: require('../assets/Images/typeno.png'),
  updatedlogo: require('../assets/Images/updatedlogo.png'),
  round: require('../assets/Images/round.png'),
  faceposition: require('../assets/Images/faceposition.png'),
  line: require('../assets/Images/line.png'),
  arrowleft: require('../assets/Images/arrowleft.png'),
  arrowr: require('../assets/Images/arrowr.png'),
  eventlogo: require('../assets/Images/eventlogo.png'),
  manimage: require('../assets/Images/manimage.png'),
  emoji: require('../assets/Images/emoji.png'),
  digit: require('../assets/Images/digit.png'),
  digitreverse: require('../assets/Images/digitreverse.png'),
  slide1: require('../assets/Images/slide1.png'),
  slide2: require('../assets/Images/slide2.png'),
  post1_s1: require('../assets/Images/post1_s1.png'),
  post2_s1: require('../assets/Images/post2_s1.png'),
  post1_s2: require('../assets/Images/post1_s2.png'),
  success: require('../assets/Images/success.png'),
  dizzy: require('../assets/Images/dizzy.png'),
  gIcon: require('../assets/Images/gIcon.png'),
};
